---

- name: "Configure shell"
  hosts: all
  gather_facts: true

  roles:
    - zsh # includes oh-my-zsh + fzf
    - liquidprompt # role related to bash if user-specific
    - lp-vg # only PS1 custom theme

  tags:
    - shell
